const suggestions = [
    {
        username: "hbarrat0",
        full_name: "Walliw Sharville",
        followed_by: "Heather Barrat",
        post: 70,
        follower: 13825,
        following: 61795,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/dddddd/000000",
    },
    {
        username: "fcrookshank1",
        full_name: "Filberte Beardow",
        followed_by: "Ferdinande Crookshank",
        post: 28,
        follower: 70150,
        following: 91703,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "adowyer2",
        full_name: "Sven Blanpein",
        followed_by: "Ambrosio Dowyer",
        post: 84,
        follower: 28792,
        following: 81570,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "bcastenda3",
        full_name: "Gnni Summerfield",
        followed_by: "Beck Castenda",
        post: 4,
        follower: 76231,
        following: 69453,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "jskelton4",
        full_name: "Sven Cambling",
        followed_by: "Josepha Skelton",
        post: 66,
        follower: 35437,
        following: 55081,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "sdottridge5",
        full_name: "Darelle Bousler",
        followed_by: "Sigismond Dottridge",
        post: 34,
        follower: 27559,
        following: 3908,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "dhumpherston6",
        full_name: "Zahara Yellowley",
        followed_by: "Desiri Humpherston",
        post: 1,
        follower: 74628,
        following: 23648,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "hchasemore7",
        full_name: "Liz Flear",
        followed_by: "Hayyim Chasemore",
        post: 21,
        follower: 67484,
        following: 61552,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "cyakushkin8",
        full_name: "Carry Rolfi",
        followed_by: "Chilton Yakushkin",
        post: 68,
        follower: 54818,
        following: 78390,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "vchamberlayne9",
        full_name: "Hugibert Heald",
        followed_by: "Vern Chamberlayne",
        post: 23,
        follower: 99127,
        following: 31304,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "mmeekea",
        full_name: "Eduard Bernhardt",
        followed_by: "Merl Meeke",
        post: 28,
        follower: 79917,
        following: 64791,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "ularverb",
        full_name: "Efren Bratten",
        followed_by: "Urban Larver",
        post: 69,
        follower: 64475,
        following: 42116,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "jsissensc",
        full_name: "Kerry Standbrook",
        followed_by: "Jessamyn Sissens",
        post: 7,
        follower: 85950,
        following: 23770,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "sbartolomeud",
        full_name: "Dorolisa Perigeaux",
        followed_by: "Sayre Bartolomeu",
        post: 92,
        follower: 42511,
        following: 17430,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "gdudleye",
        full_name: "Penn Rushforth",
        followed_by: "Geno Dudley",
        post: 22,
        follower: 34996,
        following: 72371,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "rdaughertyf",
        full_name: "Hart Spriddle",
        followed_by: "Rinaldo Daugherty",
        post: 69,
        follower: 47957,
        following: 56196,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "rheffernong",
        full_name: "Alessandro Binns",
        followed_by: "Reinald Heffernon",
        post: 16,
        follower: 10751,
        following: 85329,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "dguitelh",
        full_name: "Sigismundo Kleuer",
        followed_by: "Dael Guitel",
        post: 88,
        follower: 20796,
        following: 73033,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/dddddd/000000",
    },
    {
        username: "tdei",
        full_name: "Junie Vlahos",
        followed_by: "Timmie De Anesy",
        post: 26,
        follower: 56189,
        following: 48932,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/dddddd/000000",
    },
    {
        username: "dfurnellj",
        full_name: "Francois Turnpenny",
        followed_by: "Daniela Furnell",
        post: 16,
        follower: 62326,
        following: 39463,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "ckohrsk",
        full_name: "Shaw Cowdroy",
        followed_by: "Cindi Kohrs",
        post: 50,
        follower: 40372,
        following: 28875,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/dddddd/000000",
    },
    {
        username: "cmullesl",
        full_name: "Early Goude",
        followed_by: "Chelsae Mulles",
        post: 24,
        follower: 32209,
        following: 48249,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "kmarquetm",
        full_name: "Ethelin Cockshtt",
        followed_by: "Klement Marquet",
        post: 19,
        follower: 96295,
        following: 71752,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "clettleyn",
        full_name: "Wilmer Rounce",
        followed_by: "Cherilyn Lettley",
        post: 32,
        follower: 86000,
        following: 44432,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "gmartinetso",
        full_name: "Flint Koeppe",
        followed_by: "Graham Martinets",
        post: 25,
        follower: 13096,
        following: 81696,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "ademangeonp",
        full_name: "Jenica Willbraham",
        followed_by: "Aubrette Demangeon",
        post: 98,
        follower: 70033,
        following: 93558,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "fgobeauxq",
        full_name: "Lorry Sinderland",
        followed_by: "Frans Gobeaux",
        post: 18,
        follower: 18596,
        following: 2216,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "agolleyr",
        full_name: "Alene Campkin",
        followed_by: "Aleece Golley",
        post: 22,
        follower: 65175,
        following: 23009,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "lleneys",
        full_name: "Viole Shay",
        followed_by: "Lyndsey Leney",
        post: 15,
        follower: 30119,
        following: 10936,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "rballsdont",
        full_name: "My Bachura",
        followed_by: "Rhonda Ballsdon",
        post: 83,
        follower: 21806,
        following: 59417,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "emacrinnu",
        full_name: "Colan Van der Baaren",
        followed_by: "Edmund MacRinn",
        post: 16,
        follower: 82083,
        following: 15358,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "grootesv",
        full_name: "Giusto Orkney",
        followed_by: "Godard Rootes",
        post: 93,
        follower: 96898,
        following: 71292,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/cc0000/ffffff",
    },
    {
        username: "vblakslandw",
        full_name: "Moises Sheach",
        followed_by: "Vinny Blaksland",
        post: 42,
        follower: 16483,
        following: 55252,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "bemlinx",
        full_name: "Andree Pedro",
        followed_by: "Benny Emlin",
        post: 11,
        follower: 31580,
        following: 53102,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "rburnardy",
        full_name: "Denis Armstead",
        followed_by: "Rochella Burnard",
        post: 69,
        follower: 67576,
        following: 2590,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/dddddd/000000",
    },
    {
        username: "hrichingsz",
        full_name: "Angel Jamblin",
        followed_by: "Hewe Richings",
        post: 73,
        follower: 73897,
        following: 62691,
        isFollower: false,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "felegood10",
        full_name: "Collie Restill",
        followed_by: "Filippa Elegood",
        post: 22,
        follower: 51416,
        following: 17949,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "jtraynor11",
        full_name: "Anette Pears",
        followed_by: "Jeffie Traynor",
        post: 71,
        follower: 39071,
        following: 49400,
        isFollower: false,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/5fa2dd/ffffff",
    },
    {
        username: "tfranklyn12",
        full_name: "Chase Pigne",
        followed_by: "Tammie Franklyn",
        post: 67,
        follower: 60717,
        following: 4786,
        isFollower: true,
        follow: false,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
    {
        username: "bdymond13",
        full_name: "Derward Schuster",
        followed_by: "Barton Dymond",
        post: 3,
        follower: 35317,
        following: 48339,
        isFollower: true,
        follow: true,
        profileImg: "http://dummyimage.com/500x500.png/ff4444/ffffff",
    },
];
export default suggestions;
